package com.softdesign.devintensive.utils;

/**
 * Created by Admin on 23.06.2016.
 */
public interface ConstantManager {
    String TAG_PREFIX = "DEV ";
    String COLOR_MODE_KEY = "COLOR_MODE_KEY";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";
    String USER_PHONE_KEY = "USER_1_KEY";
    String USER_MAIL_KEY = "USER_2_KEY";
    String USER_VK_KEY = "USER_3_KEY";
    String USER_GIT_KEY = "USER_4_KEY";
    String USER_BIO_KEY = "USER_5_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    ;
    String USER_ID_KEY = "USER_ID_KEY";
    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
    String USER_RAITING_VALUE = "USER_RAITING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE = "USER_PROJECT_VALUE";
    String CONTENT_PHONE_VALUE = "CONTENT_PHONE_VALUE";
    String CONTENT_EMAIL_VALUE = "CONTENT_EMAIL_VALUE";
    String CONTENT_GIT_VALUE = "CONTENT_GIT_VALUE";
    String CONTENT_VK_VALUE = "CONTENT_VK_VALUE";
    String CONTENT_BIO_VALUE = "CONTENT_BIO_VALUE";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALERY_PICTURE = 88;

    int PERMISSION_REQUEST_SETTINGS_CODE = 101;
    int CAMERA_REQUEST_PERMISSION_CODE = 102;
    int PHONE_CALL_REQUEST_PERMISSION_CODE = 103;
}



